// <auto-generated />
using System;
using Leyadech.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leyadech.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241226171745_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Leyadech.Core.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"), 1L, 1);

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HelpKind")
                        .HasColumnType("int");

                    b.Property<bool>("IsRelevant")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("UserId");

                    b.ToTable("Aplication");

                    b.HasDiscriminator<string>("ApplicationType").HasValue("Application");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("UserType").HasValue("User");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Volunteering", b =>
                {
                    b.Property<int>("VolunteeringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteeringId"), 1L, 1);

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HelpFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("HelpKind")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("SuggestId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeStart")
                        .HasColumnType("time");

                    b.HasKey("VolunteeringId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("RequestId");

                    b.HasIndex("SuggestId");

                    b.ToTable("Volunteering");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Mother", b =>
                {
                    b.HasBaseType("Leyadech.Core.Entities.User");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChildrenBelow7")
                        .HasColumnType("int");

                    b.Property<int?>("FamilySize")
                        .HasColumnType("int");

                    b.Property<int?>("HelpKindNeeded")
                        .HasColumnType("int");

                    b.Property<bool>("IsStandingOrder")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("Mother");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Request", b =>
                {
                    b.HasBaseType("Leyadech.Core.Entities.Application");

                    b.Property<int?>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Preferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int");

                    b.ToTable("Aplication");

                    b.HasDiscriminator().HasValue("Request");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Suggest", b =>
                {
                    b.HasBaseType("Leyadech.Core.Entities.Application");

                    b.Property<int?>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("Suggest_Frequency");

                    b.Property<bool>("IsFlexible")
                        .HasColumnType("bit");

                    b.Property<string>("RelevantDays")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Aplication");

                    b.HasDiscriminator().HasValue("Suggest");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Volunteer", b =>
                {
                    b.HasBaseType("Leyadech.Core.Entities.User");

                    b.Property<int?>("HelpKindSuggested")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Volunteer_Status");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("Volunteer");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Application", b =>
                {
                    b.HasOne("Leyadech.Core.Entities.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Volunteering", b =>
                {
                    b.HasOne("Leyadech.Core.Entities.Application", null)
                        .WithMany("Volunteerings")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("Leyadech.Core.Entities.Application", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Leyadech.Core.Entities.Application", "Suggest")
                        .WithMany()
                        .HasForeignKey("SuggestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Suggest");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.Application", b =>
                {
                    b.Navigation("Volunteerings");
                });

            modelBuilder.Entity("Leyadech.Core.Entities.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
